"""Add stripe columns

Revision ID: 9e920e6fe270
Revises: 4fe615100c54
Create Date: 2026-06-09 11:29:12.216797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e920e6fe270'
down_revision: Union[str, Sequence[str], None] = '4fe615100c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'stripe_subscription_id')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###
